<?php echo $this->doctype() ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Zend Framework Demo</title>
  <link href="library/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <?php //echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
    <?php echo $this->partial('header.phtml'); ?>
    <div class="container theme-showcase" style="margin-top: 20px;">
        <?php echo $this->layout()->content ?>
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="library/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="library/bootstrap/docs/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>
