<div class="row">
    <div class="col-sm-12">
        <div class="bd-example" data-example-id="">
            <form method="post" action="">
                <fieldset class="form-group">
                    <label for="name">Full Name</label>
                    <input type="text" class="form-control" name="fullName" placeholder="Enter full name">
                    <small class="text-muted">Don't use special characters.</small>
                </fieldset>
                <fieldset class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" name='email' id="exampleInputEmail1" placeholder="Enter email">
                    <small class="text-muted">We'll never share your email with anyone else.</small>
                </fieldset>
                <fieldset class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" name='password' placeholder="Password">
                </fieldset>
                <fieldset class="form-group">
                    <label for="confirm">Confirm Password</label>
                    <input type="password" class="form-control" name='conPassword' id="exampleInputPassword1" placeholder="Confirm Password">
                
                </fieldset>
                <fieldset class="form-group">
                    <label for="exampleSelect1">User Type</label>
                    <select class="form-control" name='userType'>
                        <option value=''>Select Type</option>
                        <option value='1'>Super Admin</option>
                        <option value='2'>Admin</option>
                        <option value='3'>Normal</option>
                    </select>
                </fieldset>

                <fieldset class="form-group">
                    <label for="exampleTextarea">Description</label>
                    <textarea class="form-control" name='description' rows="3"></textarea>
                </fieldset>
                <fieldset class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <input type="file" class="form-control-file" name='image'>
                    <small class="text-muted">File should be in .png, .jpeg, .jpg</small>
                </fieldset>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>